---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-pod-example
  labels:
    app: multi-container-pod-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-container-pod-example
  template:
    metadata:
      labels:
        app: multi-container-pod-example
      annotations:
        # for multi-container-pod-example-nginx
        prometheus.io/scrape_0: "true"
        prometheus.io/port_0: "9113"
        prometheus.io/path_0: /metrics
        # for multi-container-pod-example-app
        prometheus.io/scrape_1: "true"
        prometheus.io/port_1: "28080"
        prometheus.io/path_1: /actuator/prometheus
    spec:
      containers:
        - name: multi-container-pod-example-nginx
          image: localhost:5000/multi-container-pod-example-nginx:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /liveness
              port: 18080
          readinessProbe:
            httpGet:
              path: /readiness
              port: 18080
        - name: multi-container-pod-example-app
          image: localhost:5000/multi-container-pod-example-app:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              # https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/production-ready-features.html#production-ready-kubernetes-probes
              path: /actuator/health/liveness
              port: 28080
          readinessProbe:
            httpGet:
              # https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/html/production-ready-features.html#production-ready-kubernetes-probes
              path: /actuator/health/readiness
              port: 28080

---
kind: Service
apiVersion: v1
metadata:
  name: multi-container-pod-example
spec:
  type: NodePort
  selector:
    app: multi-container-pod-example
  ports:
    - name: multi-container-pod-example-nginx
      protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 31000
